<?php
// Define the base path of your project
// If your project is in htdocs directly, use: define('BASE_URL', '/');
// If your project is in a subfolder "myproject", use:
define('BASE_URL', '/example4/');
$PAINTINGS = [
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 1',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting1.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting1'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 2',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting2.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting2'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 3',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting3.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting3'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 4',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting4.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting4'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 5',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting5.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting5'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 6',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting6.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting6'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 7',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting7.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting7'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 8',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting8.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting8'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 9',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting9.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting9'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 10',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting10.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting10'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 11',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting11.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting11'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 12',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting12.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting12'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 13',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting13.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting13'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 14',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting14.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting14'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 15',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting15.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting15'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 16',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting16.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting16'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 17',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting17.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting17'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 18',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting18.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting18'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 19',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting19.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting19'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 20',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting20.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting20'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 21',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting21.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting21'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 22',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting22.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting22'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 23',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting23.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting23'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 24',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting24.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting24'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 25',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting25.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting25'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 26',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting26.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting26'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 27',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting27.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting27'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 28',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting28.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting28'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 29',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting29.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting29'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 30',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting30.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting30'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 31',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting31.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting31'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Exhibition 32',
        'date' => '21 November 2025 – 18 January 2026',
        'location' => 'London, UK',
        'description' => `A comprehensive survey of Howardena Pindell's groundbreaking abstract paintings and mixed-media works spanning five decades.`,
        'image' => 'images/painting32.jpg',
        'category' => 'MUSEUM EXHIBITION',
        'headline' => 'Howardena Pindell: A Retrospective',
        'info' => '21 November 2025 – 18 January 2026 | London, UK',
        'link' => '/painting32'
    ]

];
