<?php

$HOME_URL = (strpos($_SERVER['HTTP_HOST'], 'localhost') !== false)
    ? '/example4/'
    : '/';

define('BASE_URL', $HOME_URL);

$ARTIST = [
    'name' => 'Yaroslav',
    'description' => 'Yaroslav is a renowned painter known for his abstract works that explore celestial energies, metropolitan landscapes, marine life, alpine vistas, and desert illusions. His paintings are featured in various galleries and museums around the world.',
    'image' => 'images/artist.jpg',
    'category' => 'CONTEMPORARY GALLERY',
    'headline' => 'Yaroslav: Cosmic Vibrations',
    'date' => '15 March 2026 – 30 May 2026',
    'location' => 'Berlin, Germany',
    'link' => '/artist-details',
    'biography' => 'Yaroslav is a renowned painter known for his abstract works that explore celestial energies, metropolitan landscapes, marine life, alpine vistas, and desert illusions. His paintings are featured in various galleries and museums around the world.'
];


$PAINTINGS = [
    [
        'artist' => 'Yaroslav',
        'title' => 'Cosmic Vibrations',
        'subtitle' => 'Celestial Energy Manifestations',
        'date' => '15 March 2026 – 30 May 2026',
        'location' => 'Berlin, Germany',
        'description' => 'An exploration of celestial energies through vibrant color fields and dynamic brushwork.',
        'long_description' => "This remarkable collection showcases Pindell's evolution from her early dot paintings to her later politically charged works. Featuring over 60 pieces, including rare archival materials and personal artifacts that reveal the artist's creative process and commitment to social justice.",
        'image' => 'images/painting1.jpg',
        'category' => 'CONTEMPORARY GALLERY',
        'headline' => 'Yaroslav: Cosmic Vibrations',
        'info' => '15 March 2026 – 30 May 2026 | Berlin, Germany',
        'link' => '/painting1'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Urban Landscapes',
        'subtitle' => 'Metropolitan Abstract Impressions',
        'date' => '5 April 2026 – 20 June 2026',
        'location' => 'New York, USA',
        'description' => "Abstract interpretations of metropolitan life through geometric forms and contrasting palettes.",
        'long_description' => "An immersive journey through Pindell's exploration of identity, race, and feminism in post-war America. This exhibition highlights her innovative use of unconventional materials and her pivotal role in the Black Arts Movement.",
        'image' => 'images/painting2.jpg',
        'category' => 'MODERN ART MUSEUM',
        'headline' => 'Yaroslav: Urban Landscapes',
        'info' => '5 April 2026 – 20 June 2026 | New York, USA',
        'link' => '/painting2'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Ocean Depths',
        'subtitle' => 'Marine Life Abstractions',
        'date' => '10 May 2026 – 25 July 2026',
        'location' => 'Sydney, Australia',
        'description' => "Fluid compositions inspired by underwater ecosystems and marine biodiversity.",
        'long_description' => "Featuring Pindell's iconic video works alongside her painted compositions, this exhibition examines how she challenged conventional boundaries between abstraction and representation throughout her distinguished career.",
        'image' => 'images/painting3.jpg',
        'category' => 'NATURAL HISTORY GALLERY',
        'headline' => 'Yaroslav: Ocean Depths',
        'info' => '10 May 2026 – 25 July 2026 | Sydney, Australia',
        'link' => '/painting3'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Mountain Echoes',
        'subtitle' => 'Alpine Resonance Series',
        'date' => '20 June 2026 – 15 August 2026',
        'location' => 'Denver, USA',
        'description' => "Majestic interpretations of alpine vistas using earth tones and textured surfaces.",
        'long_description' => "A focused presentation of Pindell's works from the 1970s, highlighting her experimentation with perforated papers and her exploration of personal narratives within abstract compositions.",
        'image' => 'images/painting4.jpg',
        'category' => 'LANDSCAPE COLLECTION',
        'headline' => 'Yaroslav: Mountain Echoes',
        'info' => '20 June 2026 – 15 August 2026 | Denver, USA',
        'link' => '/painting4'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Desert Mirage',
        'subtitle' => 'Heat Wave Illusions',
        'date' => '1 July 2026 – 20 September 2026',
        'location' => 'Dubai, UAE',
        'description' => "Heat-induced visual phenomena translated into shimmering color gradients and optical illusions.",
        'long_description' => "This thematic exhibition explores Pindell's engagement with global art movements, showcasing her unique perspective on international contemporary art and her influence on subsequent generations of artists.",
        'image' => 'images/painting5.jpg',
        'category' => 'DESERT ART INITIATIVE',
        'headline' => 'Yaroslav: Desert Mirage',
        'info' => '1 July 2026 – 20 September 2026 | Dubai, UAE',
        'link' => '/painting5'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Forest Whispers',
        'subtitle' => 'Woodland Secrets Revealed',
        'date' => '15 August 2026 – 30 October 2026',
        'location' => 'Stockholm, Sweden',
        'description' => "Organic forms and natural textures capturing the essence of woodland environments.",
        'long_description' => "An examination of Pindell's lesser-known sculptural works and installations, revealing her multidisciplinary approach and her innovative use of industrial materials in creating immersive environments.",
        'image' => 'images/painting6.jpg',
        'category' => 'ECOLOGICAL ART PROJECT',
        'headline' => 'Yaroslav: Forest Whispers',
        'info' => '15 August 2026 – 30 October 2026 | Stockholm, Sweden',
        'link' => '/painting6'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Night Sky',
        'subtitle' => 'Stellar Cartography',
        'date' => '5 September 2026 – 20 November 2026',
        'location' => 'Tokyo, Japan',
        'description' => "Starry compositions exploring celestial bodies and cosmic phenomena through abstract forms.",
        'long_description' => "A chronological presentation tracing Pindell's artistic development from her student years through her mature period, featuring early experimental works that demonstrate her innovative approach to materials and form.",
        'image' => 'images/painting7.jpg',
        'category' => 'ASTRONOMY ART EXHIBIT',
        'headline' => 'Yaroslav: Night Sky',
        'info' => '5 September 2026 – 20 November 2026 | Tokyo, Japan',
        'link' => '/painting7'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Industrial Symphony',
        'subtitle' => 'Urban Mechanical Rhythms',
        'date' => '20 October 2026 – 10 December 2026',
        'location' => 'Detroit, USA',
        'description' => "Mechanical forms and urban structures rendered in metallic hues and sharp geometries.",
        'long_description' => "Highlighting Pindell's contributions to feminist art discourse, this exhibition features works that challenge traditional gender roles and explore themes of personal and collective identity through abstract expressionism.",
        'image' => 'images/painting8.jpg',
        'category' => 'URBAN CULTURE CENTER',
        'headline' => 'Yaroslav: Industrial Symphony',
        'info' => '20 October 2026 – 10 December 2026 | Detroit, USA',
        'link' => '/painting8'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Seasonal Changes',
        'subtitle' => 'Chromatic Transitions',
        'date' => '1 November 2026 – 25 December 2026',
        'location' => 'Vienna, Austria',
        'description' => "Chromatic transitions reflecting the cyclical nature of seasonal transformations.",
        'long_description' => "An intimate look at Pindell's works on paper, showcasing her delicate mark-making and her exploration of color relationships in small-scale compositions that reveal her meticulous attention to detail.",
        'image' => 'images/painting9.jpg',
        'category' => 'CLASSICAL ART MUSEUM',
        'headline' => 'Yaroslav: Seasonal Changes',
        'info' => '1 November 2026 – 25 December 2026 | Vienna, Austria',
        'link' => '/painting9'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Water Elements',
        'subtitle' => 'Hydrodynamic Expressions',
        'date' => '10 December 2026 – 31 January 2027',
        'location' => 'Amsterdam, Netherlands',
        'description' => "Flowing forms and liquid textures representing rivers, rain, and tidal movements.",
        'long_description' => "This exhibition focuses on Pindell's large-scale canvas works from the 1980s, demonstrating her mastery of color field painting and her ability to create dynamic compositions that engage viewers on both emotional and intellectual levels.",
        'image' => 'images/painting10.jpg',
        'category' => 'HYDROLOGICAL ART GALLERY',
        'headline' => 'Yaroslav: Water Elements',
        'info' => '10 December 2026 – 31 January 2027 | Amsterdam, Netherlands',
        'link' => '/painting10'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Fire & Ice',
        'subtitle' => 'Elemental Contrasts',
        'date' => '5 January 2027 – 20 February 2027',
        'location' => 'Reykjavik, Iceland',
        'description' => "Contrasting temperatures expressed through warm reds and cool blues in dramatic compositions.",
        'long_description' => "Exploring Pindell's engagement with collage techniques, this exhibition presents her innovative combinations of painted elements with found materials, photographs, and text fragments that create layered narratives about memory and experience.",
        'image' => 'images/painting11.jpg',
        'category' => 'CLIMATE ART PROJECT',
        'headline' => 'Yaroslav: Fire & Ice',
        'info' => '5 January 2027 – 20 February 2027 | Reykjavik, Iceland',
        'link' => '/painting11'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Wind Patterns',
        'subtitle' => 'Atmospheric Currents',
        'date' => '20 February 2027 – 15 March 2027',
        'location' => 'Wellington, New Zealand',
        'description' => "Air currents visualized through sweeping brushstrokes and directional movement.",
        'long_description' => "A thematic exploration of Pindell's engagement with landscape imagery, examining how she abstracted natural forms to create compositions that evoke both personal memories and universal experiences of place and belonging.",
        'image' => 'images/painting12.jpg',
        'category' => 'ATMOSPHERIC ART EXHIBIT',
        'headline' => 'Yaroslav: Wind Patterns',
        'info' => '20 February 2027 – 15 March 2027 | Wellington, New Zealand',
        'link' => '/painting12'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Earth Tones',
        'subtitle' => 'Geological Impressions',
        'date' => '5 March 2027 – 25 April 2027',
        'location' => 'Cairo, Egypt',
        'description' => "Mineral pigments and sediment-inspired compositions reflecting geological formations.",
        'long_description' => "This exhibition showcases Pindell's series of autobiographical works created in response to her travels and cultural encounters, revealing how she synthesized global influences with her own distinctive visual language.",
        'image' => 'images/painting13.jpg',
        'category' => 'GEOLOGICAL ART INITIATIVE',
        'headline' => 'Yaroslav: Earth Tones',
        'info' => '5 March 2027 – 25 April 2027 | Cairo, Egypt',
        'link' => '/painting13'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Light Spectrum',
        'subtitle' => 'Prismatic Investigations',
        'date' => '15 April 2027 – 5 June 2027',
        'location' => 'Barcelona, Spain',
        'description' => "Prismatic breakdowns of natural and artificial illumination through pure color theory.",
        'long_description' => "Focusing on Pindell's late-career achievements, this exhibition presents her most recent works alongside archival materials that document her continued innovation and relevance in contemporary art discourse.",
        'image' => 'images/painting14.jpg',
        'category' => 'OPTICAL ART GALLERY',
        'headline' => 'Yaroslav: Light Spectrum',
        'info' => '15 April 2027 – 5 June 2027 | Barcelona, Spain',
        'link' => '/painting14'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Sound Waves',
        'subtitle' => 'Auditory Visualizations',
        'date' => '1 June 2027 – 20 July 2027',
        'location' => 'Vienna, Austria',
        'description' => "Auditory phenomena translated into visual rhythms and harmonic arrangements.",
        'long_description' => "An interdisciplinary presentation that contextualizes Pindell's work within broader art historical narratives, featuring comparative works by her contemporaries and demonstrating her influence on subsequent artistic movements.",
        'image' => 'images/painting15.jpg',
        'category' => 'SYNAESTHETIC ART MUSEUM',
        'headline' => 'Yaroslav: Sound Waves',
        'info' => '1 June 2027 – 20 July 2027 | Vienna, Austria',
        'link' => '/painting15'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Digital Dreams',
        'subtitle' => 'Cybernetic Landscapes',
        'date' => '10 July 2027 – 30 August 2027',
        'location' => 'Seoul, South Korea',
        'description' => "Virtual landscapes and cybernetic aesthetics in contemporary abstract compositions.",
        'long_description' => "This exhibition explores Pindell's use of serial imagery and repetitive mark-making as strategies for exploring themes of time, memory, and ritual in contemporary art practice.",
        'image' => 'images/painting16.jpg',
        'category' => 'TECHNOLOGICAL ART CENTER',
        'headline' => 'Yaroslav: Digital Dreams',
        'info' => '10 July 2027 – 30 August 2027 | Seoul, South Korea',
        'link' => '/painting16'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Ancient Textures',
        'subtitle' => 'Archaeological Surfaces',
        'date' => '5 August 2027 – 25 September 2027',
        'location' => 'Athens, Greece',
        'description' => "Historical surface treatments inspired by archaeological findings and classical artistry.",
        'long_description' => "A focused study of Pindell's engagement with textile traditions and fiber arts, demonstrating how she transformed craft techniques into fine art expressions that challenge hierarchical distinctions between mediums.",
        'image' => 'images/painting17.jpg',
        'category' => 'ARCHAEOLOGICAL ART EXHIBIT',
        'headline' => 'Yaroslav: Ancient Textures',
        'info' => '5 August 2027 – 25 September 2027 | Athens, Greece',
        'link' => '/painting17'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Future Visions',
        'subtitle' => 'Speculative Imaginings',
        'date' => '20 September 2027 – 15 October 2027',
        'location' => 'San Francisco, USA',
        'description' => "Speculative scenarios and imagined futures through science fiction-inspired palettes.",
        'long_description' => "Examining Pindell's exploration of geometric abstraction, this exhibition reveals how she employed mathematical principles and systematic approaches to create compositions that balance intellectual rigor with emotional resonance.",
        'image' => 'images/painting18.jpg',
        'category' => 'SCI-FI ART GALLERY',
        'headline' => 'Yaroslav: Future Visions',
        'info' => '20 September 2027 – 15 October 2027 | San Francisco, USA',
        'link' => '/painting18'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Memory Palace',
        'subtitle' => 'Nostalgic Recollections',
        'date' => '5 October 2027 – 25 November 2027',
        'location' => 'Paris, France',
        'description' => "Personal recollections reconstructed through symbolic imagery and nostalgic color schemes.",
        'long_description' => "This presentation highlights Pindell's engagement with performance art documentation, featuring photographs, videos, and ephemera that illuminate her interdisciplinary practice and collaborative spirit.",
        'image' => 'images/painting19.jpg',
        'category' => 'PSYCHOLOGICAL ART MUSEUM',
        'headline' => 'Yaroslav: Memory Palace',
        'info' => '5 October 2027 – 25 November 2027 | Paris, France',
        'link' => '/painting19'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Emotional Landscapes',
        'subtitle' => 'Psychological Terrains',
        'date' => '15 November 2027 – 10 December 2027',
        'location' => 'Florence, Italy',
        'description' => "Internal states mapped onto external terrains through expressive color relationships.",
        'long_description' => "A thematic investigation of Pindell's color theories and palettes, this exhibition demonstrates how she employed chromatic relationships to create psychological and spatial effects that enhance the expressive power of her abstract compositions.",
        'image' => 'images/painting20.jpg',
        'category' => 'EMOTIONAL ART PROJECT',
        'headline' => 'Yaroslav: Emotional Landscapes',
        'info' => '15 November 2027 – 10 December 2027 | Florence, Italy',
        'link' => '/painting20'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Architectural Forms',
        'subtitle' => 'Structural Compositions',
        'date' => '5 December 2027 – 25 January 2028',
        'location' => 'Chicago, USA',
        'description' => "Built environments abstracted into structural compositions and spatial investigations.",
        'long_description' => "This exhibition explores Pindell's interest in architectural space and environmental installation, presenting works that investigate the relationship between art objects and their surrounding contexts.",
        'image' => 'images/painting21.jpg',
        'category' => 'ARCHITECTURAL ART GALLERY',
        'headline' => 'Yaroslav: Architectural Forms',
        'info' => '5 December 2027 – 25 January 2028 | Chicago, USA',
        'link' => '/painting21'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Botanical Studies',
        'subtitle' => 'Floral Investigations',
        'date' => '20 January 2028 – 15 March 2028',
        'location' => 'Rio de Janeiro, Brazil',
        'description' => "Floral and plant life captured through organic shapes and naturalistic coloration.",
        'long_description' => "Focusing on Pindell's experimental printmaking techniques, this exhibition reveals her innovative approaches to reproductive media and her exploration of multiples as a democratic form of artistic expression.",
        'image' => 'images/painting22.jpg',
        'category' => 'BOTANICAL ART INITIATIVE',
        'headline' => 'Yaroslav: Botanical Studies',
        'info' => '20 January 2028 – 15 March 2028 | Rio de Janeiro, Brazil',
        'link' => '/painting22'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Animal Kingdom',
        'subtitle' => 'Wildlife Expressions',
        'date' => '5 March 2028 – 25 April 2028',
        'location' => 'Cape Town, South Africa',
        'description' => "Wildlife behaviors and characteristics expressed through dynamic gestural forms.",
        'long_description' => "An examination of Pindell's engagement with photographic imagery and appropriation strategies, showcasing how she incorporated found images into her mixed-media works to create layered commentaries on media culture and representation.",
        'image' => 'images/painting23.jpg',
        'category' => 'ZOological ART EXHIBIT',
        'headline' => 'Yaroslav: Animal Kingdom',
        'info' => '5 March 2028 – 25 April 2028 | Cape Town, South Africa',
        'link' => '/painting23'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Human Condition',
        'subtitle' => 'Existential Explorations',
        'date' => '15 April 2028 – 10 June 2028',
        'location' => 'Geneva, Switzerland',
        'description' => "Existential themes explored through figurative abstractions and emotional expressions.",
        'long_description' => "This exhibition presents Pindell's works that engage with themes of displacement and diaspora, exploring how her personal experiences of migration informed her broader investigations into identity and belonging.",
        'image' => 'images/painting24.jpg',
        'category' => 'PHILOSOPHICAL ART MUSEUM',
        'headline' => 'Yaroslav: Human Condition',
        'info' => '15 April 2028 – 10 June 2028 | Geneva, Switzerland',
        'link' => '/painting24'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Time Portals',
        'subtitle' => 'Temporal Transitions',
        'date' => '5 June 2028 – 25 July 2028',
        'location' => 'London, UK',
        'description' => "Temporal shifts visualized through layered compositions and historical references.",
        'long_description' => "A focused presentation of Pindell's works that incorporate text and language, examining how she employed written elements to create conceptual frameworks that guide viewer interpretation of her abstract compositions.",
        'image' => 'images/painting25.jpg',
        'category' => 'TEMPORAL ART PROJECT',
        'headline' => 'Yaroslav: Time Portals',
        'info' => '5 June 2028 – 25 July 2028 | London, UK',
        'link' => '/painting25'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Cultural Mosaic',
        'subtitle' => 'Multicultural Tapestry',
        'date' => '20 July 2028 – 15 August 2028',
        'location' => 'Istanbul, Turkey',
        'description' => "Multicultural influences blended into harmonious compositions celebrating diversity.",
        'long_description' => "This exhibition investigates Pindell's engagement with musical structures and rhythms, revealing how she translated auditory experiences into visual forms through her innovative use of repetition and variation.",
        'image' => 'images/painting26.jpg',
        'category' => 'MULTICULTURAL ART GALLERY',
        'headline' => 'Yaroslav: Cultural Mosaic',
        'info' => '20 July 2028 – 15 August 2028 | Istanbul, Turkey',
        'link' => '/painting26'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Spiritual Journeys',
        'subtitle' => 'Transcendent Paths',
        'date' => '5 August 2028 – 25 September 2028',
        'location' => 'Varanasi, India',
        'description' => "Transcendent experiences depicted through ethereal forms and luminous color fields.",
        'long_description' => "An exploration of Pindell's engagement with scientific imagery and concepts, showcasing works that reflect her fascination with cellular structures, molecular formations, and natural phenomena as sources for abstract composition.",
        'image' => 'images/painting27.jpg',
        'category' => 'SPIRITUAL ART INITIATIVE',
        'headline' => 'Yaroslav: Spiritual Journeys',
        'info' => '5 August 2028 – 25 September 2028 | Varanasi, India',
        'link' => '/painting27'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Social Constructs',
        'subtitle' => 'Societal Frameworks',
        'date' => '15 September 2028 – 10 October 2028',
        'location' => 'Johannesburg, South Africa',
        'description' => "Societal frameworks examined through critical commentary and conceptual installations.",
        'long_description' => "This exhibition examines Pindell's mentorship role and educational contributions, featuring works by artists she influenced alongside her own pieces to demonstrate her lasting impact on contemporary art pedagogy.",
        'image' => 'images/painting28.jpg',
        'category' => 'SOCIOLOGICAL ART EXHIBIT',
        'headline' => 'Yaroslav: Social Constructs',
        'info' => '15 September 2028 – 10 October 2028 | Johannesburg, South Africa',
        'link' => '/painting28'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Political Statements',
        'subtitle' => 'Activist Narratives',
        'date' => '5 October 2028 – 25 November 2028',
        'location' => 'Washington D.C., USA',
        'description' => "Activist art addressing contemporary issues through powerful visual narratives.",
        'long_description' => "A chronological presentation of Pindell's works that address social and political issues, demonstrating how she evolved her visual vocabulary to confront changing historical circumstances while maintaining her commitment to abstract expression.",
        'image' => 'images/painting29.jpg',
        'category' => 'POLITICAL ART MUSEUM',
        'headline' => 'Yaroslav: Political Statements',
        'info' => '5 October 2028 – 25 November 2028 | Washington D.C., USA',
        'link' => '/painting29'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Philosophical Inquiries',
        'subtitle' => 'Metaphysical Questions',
        'date' => '20 November 2028 – 15 December 2028',
        'location' => 'Oxford, UK',
        'description' => "Metaphysical questions explored through abstract reasoning and conceptual frameworks.",
        'long_description' => "This culminating exhibition presents Pindell's most recent works in dialogue with pieces from throughout her career, revealing the continuity of her artistic vision and her ongoing relevance to contemporary debates about art and society.",
        'image' => 'images/painting30.jpg',
        'category' => 'PHILOSOPHICAL ART GALLERY',
        'headline' => 'Yaroslav: Philosophical Inquiries',
        'info' => '20 November 2028 – 15 December 2028 | Oxford, UK',
        'link' => '/painting30'
    ],
    [
        'artist' => 'Yaroslav',
        'title' => 'Universal Truths',
        'subtitle' => 'Essential Principles',
        'date' => '5 December 2028 – 31 January 2029',
        'location' => 'Kyoto, Japan',
        'description' => "Fundamental principles expressed through minimalist compositions and meditative forms.",
        'long_description' => "A special installation featuring Pindell's collaborative projects with fellow artists and community organizations, highlighting her dedication to collective creativity and her belief in art's capacity to foster social change.",
        'image' => 'images/painting31.jpg',
        'category' => 'ESSENTIAL ART PROJECT',
        'headline' => 'Yaroslav: Universal Truths',
        'info' => '5 December 2028 – 31 January 2029 | Kyoto, Japan',
        'link' => '/painting31'
    ],
];
